# Generated by Django 3.2.7 on 2021-10-13 12:11

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kun', '0002_alter_modelmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmodel',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='rightmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='rightmodel',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
