# Generated by Django 3.2.7 on 2021-10-13 13:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kun', '0003_auto_20211013_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmodel',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rightmodel',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
