# Generated by Django 3.2.7 on 2021-09-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('posted_by', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.IntegerField(default=1)),
                ('liked_by', models.IntegerField(default=-1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yangiliklar.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=270)),
                ('commented_by', models.IntegerField(default=-1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yangiliklar.post')),
            ],
        ),
    ]
