# Generated by Django 3.2.7 on 2021-09-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='post',
            table='News',
        ),
    ]
