# Generated by Django 3.2.7 on 2021-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0002_auto_20210925_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default='ovewview'),
            preserve_default=False,
        ),
    ]
